### ISSUE TITLE
7.4 formulas

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#33] opened 2016-08-22 20:56 UTC
# melee/distance formula

- [x] **player melee max value**
```
https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/weapons.cpp#L146
((attackValue * attackSkill * 0.06) / attackFactor)
```

- [x] **player distance min value**
```
https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/weapons.cpp#L838
```
_not tested.._

- [ ] **player distance max value**
`((attackValue * attackSkill * 0.065) / attackFactor)`
_not tested.._

- [ ] **monster melee max value**
`https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/weapons.cpp#L137`
_not tested.._

- [ ] **monster distance max value**
_not tested.._

# hit chance formula for weapons and ammunition

- [ ] hit chance for weapons
```
https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/weapons.cpp#L630
```

_not tested.._

- [ ] arrow - `25 atk, hit chance: 90%, range: 6 (bow)`
- [ ] burst arrow - `formula, hit chance: 80%, range: 6 (bow)`
- [ ] poison arrow - `20 atk, hit chance: 80%, range: 6 (bow)`
- [ ] bolt - `30 atk, hit chance: 80%, range: 5 (crossbow)`
- [ ] power bolt - `40 atk, hit chance: none, range: 5 (crossbow)`
- [ ] small stone - `5 atk, hit chance: none, range: 5`
- [ ] spear - `25 atk, hit chance: none, range: 5`
- [ ] snowball - `0 atk, hit chance: none, range: 5`
- [ ] throwing star - `30 atk, hit chance: none, range: 5`
- [ ] throwing knife - `25 atk, hit chance, none, range: 5`

_not tested.._

# break rate
- [x] break reate for weapons

`small stones, spears, throwing stars and throwing knifes doesn't have a break rate, they do however land on the ground and doesn't come back, also snowballs gets removed.`

# armor and shielding formula
`https://github.com/babymannen/theforgottenserver-7.4/blob/1e1ae353bcd2ca0183f898ac9f1b42a931e96124/src/creature.cpp#L890
`
- [ ] armorFormula = armorValue * 0.475;

_not tested.._

# attack spells formula
- [ ]  berserk
- [ ]  energy beam
- [x]  energy field
- [ ]  energy strike
- [x]  energy wall
- [ ]  energy wave
- [x]  energy bomb
- [ ]  envenom
- [ ]  explosion
- [x]  fire field
- [x]  fire wall
- [ ]  fire wave
- [ ]  fireball
- [x]  fire bomb
- [ ]  flame strike
- [ ]  force strike
- [ ]  great energy beam
- [x]  great fireball
- [x]  heavy magic missile
- [ ]  light magic missile
- [x]  poison bomb
- [x]  poison field
- [ ]  poison storm
- [x]  poison wall
- [ ]  soulfire
- [x]  sudden death
- [ ]  ultimate explosion

_not tested.._

# healing spells formula
- [ ]  antidote rune
- [ ]  antidote
- [ ]  heal friend
- [ ]  intense healing rune
- [ ]  intense healing
- [ ]  light healing
- [ ]  mass healing
- [ ]  ultimate healing rune
- [ ]  ultimate healing

_not tested.._

# support spells formula
- [ ]  animate dead rune
- [ ]  cancel invisibility
- [ ]  challenge
- [ ]  desintegrate rune
- [ ]  destroy field rune
- [ ]  food
- [ ]  great light
- [ ]  haste
- [ ]  invisible
- [ ]  light
- [ ]  magic rope
- [ ]  magic shield
- [ ]  magic wall rune
- [ ]  paralyze rune
- [ ]  strong haste
- [ ]  ultimate light
- [ ]  undead legion
- [ ]  wild growth

_not tested.._

# speed formula
`https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/player.h#L1090`

http://peonso.co.nf/oldschool/mechanics.php#speed

_not tested.._

# monster paralyze formula
- [ ] warlock
- [ ] vampire
- [ ] mummy
- [ ] marid
- [ ] lich
- [ ] hydra
- [ ] elder beholder
- [ ] efreet
- [ ] dworc voodoomaster
- [ ] carniphila
- [ ] banshee
- [ ] ancient scarab

_not tested.._

# monster haste formula
- [ ] wild warrior
- [ ] tiger
- [ ] tarantula
- [ ] sibang
- [ ] serpent spawn
- [ ] scarab
- [ ] orc rider
- [ ] orc berserker
- [ ] monk
- [ ] kongra
- [ ] giant spider
- [ ] gazer
- [ ] dworc voodoomaster
- [ ] dark monk
- [ ] behemoth
- [ ] assassin
- [ ] ancient scarab

_not tested.._

# fluids
- [x] mana fluid - `restored between 20-75 mana, costed 100gp`
- [x] life fluid - `restored 60 health, costed 65gp`

_not tested.._

# items
- [ ] life ring - `20 minutes - 400 mana (1mana/3sec) - 400 hp (1hp/3sec)`
- [ ] ring of healing
- [ ] pair of soft boots

_not tested.._

# vocation regens
- [x] knight - `1hp/6sec, 1mana/12sec` / elite knight - `1hp/4sec, 1mana/12sec`
- [x] paladin - `1hp/8sec, 1mana/8sec` / royal paladin - `1hp/6sec, 1mana/6sec`
- [x] druid - `1hp/12sec, 1mana/6sec ` / elder druid - `1hp/12sec, 1mana/4sec`
- [x] sorcerer - `1hp/12sec, 1mana/6sec` / master sorcerer - `1hp/12sec, 1mana/4sec`

_not tested.._

**Comment by peonso** [comment] 2016-08-22 21:05
You might find stuff here
http://peonso.co.nf/oldschool/mechanics.php
https://otland.net/threads/game-mechanics-through-time.216072/

**Comment by Seliro** [comment] 2016-08-22 21:25
moved those down here for now

distance - http://web.archive.org/web/20150609095041/http://tibianic.org/forum/topic/8512/1/ 
melee - http://web.archive.org/web/20150609095204/http://tibianic.org/forum/topic/8511/1/
armor - http://web.archive.org/web/20150609095241/http://tibianic.org/forum/topic/8513/1/
shielding - http://web.archive.org/web/20150609095305/http://tibianic.org/forum/topic/8514/1/
hit chance? - http://web.archive.org/web/20100209081857/http://tibianews.net/article.asp?Id=429
probably the same as above - https://github.com/TwistedScorpio/OTHire/wiki/Combat-Formulas

**Comment by peonso** [comment] 2016-08-22 21:36
I don't think you can find better spell formulas then the ones I already submitted. 
https://docs.google.com/spreadsheets/d/1293KCxxpovzlJk6QAnrZ52Hgr9LA_H5YlMPhgEhGS8s/edit?usp=sharing

**Comment by Seliro** [comment] 2016-08-22 21:41
you can edit my issue right?, if so feel free to edit what you know is correct already

**Comment by Seliro** [comment] 2016-08-22 21:54
is exhausts correct btw?

**Comment by peonso** [comment] 2016-08-22 21:56
I'm 100% just about HMM, GFB, SD. The problem is how to figure out the rest. People say exori vis/flam/mort has 1000 exhaust, I never got to verify that, all support/healing spells got 1s exhaust, attack got 2s.

**Comment by Seliro** [comment] 2016-08-22 22:06
il copy the list of spells and make a new issue for exhausts and we can check on it after, ok?

**Comment by babymannen** [comment] 2016-09-10 00:03
I don't see this as an issue with the server itself. Please commit all the changes and Peonso or me will push  them. Closing

**Closed by babymannen** 2016-09-10 00:03 UTC
